# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
      - refs/tags/*

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: GitVersion@5
  displayName: 'Git Version'
  
- task: Docker@2
  inputs:
    containerRegistry: 'PoweredSoftDockerHub'
    repository: 'poweredsoft/mysql-docker-backup'
    command: 'buildAndPush'
    Dockerfile: 'PoweredSoft.Docker.MysqlBackup/Dockerfile'
    tags: |
      latest
      $(GitVersion.NugetVersion)